language: c
install: bash -e .travis-ci-install.sh
script: bash -e .travis-ci.sh
cache: apt
dist: trusty
sudo: required
matrix:
  include:
  - os: osx
    osx_image: xcode7.3
    env: OCAML_VERSION=4.06 OPAM_VERSION=2.0.0
